SITE = {
    "title": "吕晓维 | 产品设计师",
    "description": "吕晓维，产品设计师，10年工作经验，长期负责复杂业务场景中的体验与策略设计。",
    "email": "mailto:konmarzec2@gmail.com",
    "socials": [
        ("Email", "mailto:konmarzec2@gmail.com"),
        ("LinkedIn", "https://www.linkedin.com/in/konmarzec/"),
        ("Medium", "https://medium.com/@konmarzec2"),
        ("Instagram", "https://www.instagram.com/mrmarch.design/"),
    ],
    "location": "Singapore",
    "timezone": "Asia/Singapore",
    "brand_mark_light": "/assets/custom/avatar.jpg",
    "brand_mark_dark": "/assets/custom/avatar.jpg",
}


CASE_STUDIES = [
    {
        "slug": "solace",
        "eyebrow": "GovTech · iOS app",
        "title": "Solace",
        "summary": "Deliver AI-driven companionship and emotional support through visually engaging conversations.",
        "card_media": "/assets/framer/images/cD8kmAdNRPw0aGaguLS1eL1SE-f46666c19f.png",
        "hero_media": "/assets/framer/images/3ZyZ30ausFucl0v2XeRFDO7m7k-4fa4b57552.png",
        "problem": "Build an emotionally warm AI companion concept that feels expressive, trustworthy, and accessible from the very first interaction.",
        "details": [
            ("My role", "Sole designer"),
            ("Duration", "34h"),
            ("Responsibilities", "End-to-end process"),
            ("Tools", "Midjourney"),
        ],
        "highlights": [
            ("4/5", "User satisfaction score"),
            ("60+", "AI companions"),
            ("70+", "Screens explored"),
        ],
        "sections": [
            {
                "chapter": "Chapter 1",
                "title": "Discovery",
                "tags": ["Market research", "Competitive analysis", "Archetypes & journeys"],
                "body": "Secondary research surfaced a clear opportunity: many people experience loneliness, stress, or stigma around mental health support, but still want something gentle, private, and easy to access.",
                "note": "1 in 3 Singaporeans report mental health struggles, and nearly 50% of seniors report feeling lonely.",
            },
            {
                "chapter": "Chapter 2",
                "title": "Branding",
                "tags": ["Identity system", "Character language", "Typography"],
                "body": "The visual system was built around soft gradients, confident typography, and character personalities that made the product feel alive without becoming cartoonish.",
            },
            {
                "chapter": "Chapter 3",
                "title": "Wireframes",
                "tags": ["Conversation flows", "Companion browsing", "Prompt states"],
                "body": "I explored lightweight entry points, clear emotional framing, and visual reactions that made real-time conversations feel calmer and more supportive.",
            },
            {
                "chapter": "Chapter 4",
                "title": "Evaluative research",
                "tags": ["Guerrilla user testing"],
                "body": "Participants responded positively to the concept, but some felt the empathetic tone could sound scripted. That pushed the iteration toward more flexible tone and stronger emotional nuance.",
                "note": "“Sometimes the replies feel too robotic. I want it to feel more natural.”",
            },
            {
                "chapter": "Chapter 5",
                "title": "Solutions & iterations",
                "tags": ["Real-time conversations", "Character reviews", "Accessibility"],
                "body": "The final direction emphasized expressive reactions, a wide set of companions, and personality previews so users could choose the type of emotional support that felt right for them.",
            },
            {
                "chapter": "Chapter 6",
                "title": "UX motion",
                "tags": ["Micro-interactions", "Prototype polish"],
                "body": "Motion was used to soften transitions, make the interface feel attentive, and reinforce the sense that every companion was responding in the moment.",
            },
        ],
        "gallery": [
            ("/assets/framer/images/5DOGp5jn95PqW8X5HzfAQXAco-0bcfb0d260.png", "image"),
            ("/assets/framer/images/NMBtbrgn9NFZKkTO0y5qUKmkI-9f42ed117a.png", "image"),
            ("/assets/framer/images/BHliekImhGkXo59kDESxjORH5CQ-288216817c.png", "image"),
            ("/assets/framer/images/UK3u3zXV3TT643fpVODBFvEt2I-6646792158.png", "image"),
            ("/assets/framer/images/0lir15GaYfpRoTr2ZzTlImDD6iE-fb70674cd8.png", "image"),
            ("/assets/framer/images/rrwDZVypN3sBcWE3S8L9eOQyld4-278a2a84f2.png", "image"),
            ("/assets/framer/images/L1aba2QxSyRtJBjH7du4g59I-2a4fb7870c.png", "image"),
            ("/assets/framer/images/EmBz8FJz7Dj0aMPcumlGK5T68-067f26fe1f.png", "image"),
            ("/assets/framer/assets/kswp2panaquv0BUBCkkB6LFg24.mp4", "video"),
            ("/assets/framer/images/NRzGnbmz1MX45WhN7UuFO9Lly3s-63e5760678.png", "image"),
            ("/assets/framer/assets/8pvXQJKWFSEFHo75uPtCgiZanI.mp4", "video"),
        ],
        "retrospective": [
            "The emotional tone needed more variation than the first prototype suggested.",
            "Character choice became a stronger product surface than expected.",
            "Motion was essential for making the experience feel less transactional.",
        ],
    },
    {
        "slug": "work-well-being",
        "eyebrow": "Indeed · cross-platform",
        "title": "Work Wellbeing Index",
        "summary": "Establish a standard for measuring and improving Work Wellbeing.",
        "card_media": "/assets/framer/images/JNql6J4f2ORE9KsQ7ltTswZ4RpA-4994643a69.png",
        "hero_media": "/assets/framer/images/JNql6J4f2ORE9KsQ7ltTswZ4RpA-4994643a69.png",
        "problem": "Translate a broad ESG commitment into a product experience that helps job seekers understand, compare, and act on wellbeing signals while searching.",
        "details": [
            ("My role", "Lead designer"),
            ("Duration", "3 quarters"),
            ("Responsibilities", "End-to-end process"),
            ("Featured in", "Fast Company award finalist"),
        ],
        "highlights": [
            ("5.5M", "Work Wellbeing ratings collected"),
            ("16M", "Visitors per month"),
            ("14", "Countries launched"),
        ],
        "sections": [
            {
                "chapter": "Chapter 1",
                "title": "Discovery",
                "tags": ["Stakeholder interviews", "Survey", "User interviews"],
                "body": "The initiative sat at the intersection of business, policy, and product. Research aligned the team around how job seekers interpret wellbeing and why it matters during moments of uncertainty.",
                "note": "The program became part of Indeed’s 2030 ESG commitments and was refined with academics from Oxford.",
            },
            {
                "chapter": "Chapter 2",
                "title": "Ideation",
                "tags": ["Wireframes", "Design explorations"],
                "body": "The core challenge was turning an abstract concept into something readable and comparable. I explored scales, scoring systems, and employer storytelling patterns that felt actionable instead of academic.",
            },
            {
                "chapter": "Chapter 3",
                "title": "Evaluative research",
                "tags": ["User testing"],
                "body": "Participants quickly understood the premise and could articulate how wellbeing data might change the way they search, filter, and compare opportunities.",
            },
            {
                "chapter": "Chapter 4",
                "title": "Hi-fi design",
                "tags": ["Scoring model", "Visualization"],
                "body": "The final UI balanced a clear total score with dimension-level breakdowns such as flexibility, inclusion, trust, appreciation, and purpose.",
            },
            {
                "chapter": "Chapter 5",
                "title": "Iterations",
                "tags": ["Preference collection", "Ranking", "Verbatim comments"],
                "body": "Later iterations focused on letting job seekers express their priorities, rank companies more meaningfully, and understand the reasons behind each score through qualitative comments.",
            },
        ],
        "gallery": [
            ("/assets/framer/images/lY772bOzqoOSa1j1vp31stYMk-b186ed9d78.svg", "image"),
            ("/assets/framer/images/WdfaATuq4xuJiHNVHyLTJPr1rY-b186ed9d78.svg", "image"),
            ("/assets/framer/images/XTFWhYPXfBckEFF3JnBMxmo1U-b186ed9d78.svg", "image"),
            ("/assets/framer/images/x9fKA83nZu8ByeMAw00itP9VAGo-bf9dc22c72.png", "image"),
            ("/assets/framer/images/NOrB05Zrd8aHAIgIBCK1ysNzHso-54379b0dd2.png", "image"),
            ("/assets/framer/images/vWNBwUbirCagE2OK8V6NspKUg6g-727b4af03b.png", "image"),
            ("/assets/framer/assets/fwczANSbZL8ZoSK2PUGRvv3pU.mp4", "video"),
            ("/assets/framer/images/jljvJ68Ts1xTEmyQPZ1N6UBmJ6g-22ae95bda7.png", "image"),
            ("/assets/framer/images/nzqFwEIrSYMwK4oioztNHyxhXM-60d9f60dc1.png", "image"),
            ("/assets/framer/assets/bXkAfQTkjFIZMymiqTx6PRDKdo.mp4", "video"),
        ],
        "retrospective": [
            "A shared definition of wellbeing was necessary before interface work could move quickly.",
            "Qualitative comments made the quantitative model feel much more believable.",
            "Preference capture became a key bridge between abstract scoring and practical job search decisions.",
        ],
    },
    {
        "slug": "parkit",
        "eyebrow": "GovTech · enterprise webapp",
        "title": "Parkit",
        "summary": "Improve officers' satisfaction and productivity with car park management tools.",
        "card_media": "/assets/framer/images/BCY2H9fkiujjLvpZedCLbdQADI-95fd02fd93.png",
        "hero_media": "/assets/framer/images/9rkAecpGN7zVRlIr109og4zNkxA-bafaf82181.png",
        "problem": "Modernize a long-neglected internal system so officers can work faster, trust the data, and feel less friction throughout their daily tasks.",
        "details": [
            ("My role", "Sole designer"),
            ("Duration", "4 quarters"),
            ("Responsibilities", "End-to-end process"),
            ("Team context", "Maintenance product moving to a new platform"),
        ],
        "highlights": [
            ("20%", "Increase in user satisfaction"),
            ("27%", "Reduced time spent on tasks"),
            ("160+", "Screens designed"),
        ],
        "sections": [
            {
                "chapter": "Chapter 1",
                "title": "Discovery",
                "tags": ["Stakeholder interviews", "User interviews", "Heuristic evaluation"],
                "body": "The project started with operational pain points: outdated workflows, unreliable patterns, and years of deprioritization that left officers with frustrating tools.",
            },
            {
                "chapter": "Chapter 2",
                "title": "Strategy",
                "tags": ["Value proposition", "Vision", "Roadmap"],
                "body": "I framed the work in phases so the team could simultaneously fix broken fundamentals, migrate the platform, and introduce new capabilities with confidence.",
            },
            {
                "chapter": "Chapter 3",
                "title": "Guidelines & libraries",
                "tags": ["Brand expressions", "Design system"],
                "body": "A small but focused component system helped the product feel modern and consistent, which also made future internal expansion easier.",
            },
            {
                "chapter": "Chapter 4",
                "title": "Design",
                "tags": ["Information architecture", "User flows & wireframes"],
                "body": "The information architecture was simplified around the tasks officers do most often, reducing hunting, mode switching, and ambiguity in the interface.",
            },
            {
                "chapter": "Chapter 5",
                "title": "Evaluative research",
                "tags": ["User testing"],
                "body": "Participants called out the comprehensiveness of the new direction and asked when they could start using it, which gave the team confidence to move into implementation.",
                "note": "“This is very comprehensive. When can we use it?”",
            },
            {
                "chapter": "Chapter 6",
                "title": "Phase 1",
                "tags": ["Prototype review"],
                "body": "The first release focused on foundations and core workflows before the more advanced operational tools were layered on top.",
            },
            {
                "chapter": "Chapter 7",
                "title": "Phase 2",
                "tags": ["Map", "Lots allocation", "Data visualization"],
                "body": "The second phase expanded the system into richer planning surfaces, giving teams better spatial awareness and more efficient decision support.",
            },
        ],
        "gallery": [
            ("/assets/framer/images/iWxSnXT1pSrqW0djtmvYxwcIGLE-f273f3088d.png", "image"),
            ("/assets/framer/images/3EluHWnflqJU4uOuq8pNVNTwLM-9834a7fcd4.png", "image"),
            ("/assets/framer/images/E5cixQBM476KKXVMfjZBcI6cqx0-9834a7fcd4.png", "image"),
            ("/assets/framer/images/Wm15YUM0y2K1Ya4oeXCPktLxr0-c86f064a09.png", "image"),
            ("/assets/framer/images/Wp7fm4E4SV9pC4ZP0kZIjTb0-3799ad4e76.png", "image"),
            ("/assets/framer/images/8gGMqGtkDxdpgVLtjZzVWTLmXI-eca7b78d70.png", "image"),
            ("/assets/framer/images/t28q0aFH6NVnTB9hcRflDc8lMI-6e2d3250f6.png", "image"),
            ("/assets/framer/images/fWa1SOsOLXZtclowixHg2gKRo-7c97bc9e6b.png", "image"),
            ("/assets/framer/images/o9L4mTImzyQMNURhsjIBnyFcTYs.png", "image"),
            ("/assets/framer/images/9KqHvgFWiWUVVlDjj1soAXXKok-c3a38e975d.png", "image"),
        ],
        "retrospective": [
            "A neglected internal product needed trust-building as much as feature design.",
            "Phased delivery kept momentum while a new platform was taking shape.",
            "A modest design system had outsized impact on clarity and speed.",
        ],
    },
    {
        "slug": "grab",
        "eyebrow": "Grab · native apps",
        "title": "Help Centre",
        "summary": "Deliver accessible and personalized support with a seamless in-app help centre.",
        "card_media": "/assets/framer/images/L1PoQ8rrcKIj80ppOVUIl196jZg-b58fbb08f9.png",
        "hero_media": "/assets/framer/images/G5sFAyNkDPjwImT2YR9vBlH2wMc-b11f391602.png",
        "problem": "Reduce support friction by helping people solve the right problem quickly, in context, without getting lost in a generic support maze.",
        "details": [
            ("My role", "Lead designer"),
            ("Duration", "3 quarters"),
            ("Responsibilities", "End-to-end process"),
            ("Platforms", "Native mobile experiences"),
        ],
        "highlights": [
            ("50%", "Reduction in page views"),
            ("25%", "Increase in user satisfaction"),
            ("46%", "Self-service success rate"),
        ],
        "sections": [
            {
                "chapter": "Chapter 1",
                "title": "Discovery",
                "tags": ["Feedback analysis", "Contextual inquiry"],
                "body": "Support pain points were highly repetitive, but the product experience around them was fragmented. The discovery phase focused on understanding which complaints mattered most and where people got stuck.",
            },
            {
                "chapter": "Chapter 2",
                "title": "Strategy",
                "tags": ["Vision", "Objectives", "Success metrics"],
                "body": "The strategy centered on localized, accessible, and personalized self-service that could improve satisfaction while reducing support load over time.",
            },
            {
                "chapter": "Chapter 3",
                "title": "Prioritization",
                "tags": ["Roadmap", "Milestones"],
                "body": "Instead of redesigning everything at once, the roadmap focused first on a few high-frequency issues and scaled outward after the strongest patterns were working well.",
            },
            {
                "chapter": "Chapter 4",
                "title": "Information architecture",
                "tags": ["Card sorting"],
                "body": "The IA was restructured around the language users naturally use when they need help, making paths easier to scan and less dependent on internal terminology.",
            },
            {
                "chapter": "Chapter 5",
                "title": "Design",
                "tags": ["User flows", "Wireframes"],
                "body": "The interface design emphasized contextual entry points, clearer status communication, and progressive disclosure so people could move from confusion to resolution faster.",
            },
            {
                "chapter": "Chapter 6",
                "title": "Evaluative research",
                "tags": ["Usability test"],
                "body": "Research showed that the redesigned support surfaces reduced wandering, helped people understand what to do next, and improved confidence in self-service.",
            },
            {
                "chapter": "Chapter 7",
                "title": "Launch & iterations",
                "tags": ["Information centre", "AI chatbot"],
                "body": "After launch, the experience expanded into more proactive information surfaces and AI-assisted support concepts while staying grounded in contextual relevance.",
            },
        ],
        "gallery": [
            ("/assets/framer/images/0AwDzVebidQd2FNAYbtm0Mxonec-060a420249.png", "image"),
            ("/assets/framer/images/vyPy9Z1bYUl9KUWm4Avdkf8Y-54379b0dd2.png", "image"),
            ("/assets/framer/images/WyBcz6O5qR7SyUNTaFIJLlJCwNc-89eea55a72.png", "image"),
            ("/assets/framer/images/HQnnR1GgXSgPKDPMNJGWUzlmFE-90d10a0c38.png", "image"),
            ("/assets/framer/images/Pmn0fRDZBFVTgMJqLzFDQURU8Q-90d10a0c38.png", "image"),
            ("/assets/framer/images/6AXohAK1Vlb2mpc5vQ9bCOtpg-e95e414027.png", "image"),
            ("/assets/framer/assets/V7hLKckpdk8cFzlMz7aABsB7znM.mp4", "video"),
            ("/assets/framer/images/juZobkaEWffriM57RPyfFUPSc-508876a0bd.png", "image"),
            ("/assets/framer/assets/TSMvBd3LF05ABL4K5He5ORyMy4.mp4", "video"),
            ("/assets/framer/images/32luDpeh9JBHrZ6d5c1IOj2rA0-90d10a0c38.png", "image"),
        ],
        "retrospective": [
            "Context mattered more than a giant knowledge base.",
            "Localized language choices were essential to trust.",
            "Support UX improved fastest when tied to real complaint frequency data.",
        ],
    },
    {
        "slug": "career-explorer",
        "eyebrow": "Indeed · cross-platform",
        "title": "Career Explorer",
        "summary": "A one-stop destination for all content related to occupations and careers.",
        "card_media": "/assets/framer/images/l0G3ysZsQif1uzpE8jHvhhE2g-4b3bebf2a0.png",
        "hero_media": "/assets/framer/images/T2pH9aSYskMjFsG7NrPNR8bZE8-3799ad4e76.png",
        "problem": "Turn fragmented career content into a coherent destination that helps people understand pathways, skills, and next steps with confidence.",
        "details": [
            ("My role", "Lead designer"),
            ("Duration", "4 quarters"),
            ("Responsibilities", "End-to-end process"),
            ("Scope", "Large content ecosystem"),
        ],
        "highlights": [
            ("5M+", "Visitors per month"),
            ("2%", "Job applies growth"),
            ("26", "Countries"),
        ],
        "sections": [
            {
                "chapter": "Chapter 1",
                "title": "Discovery",
                "tags": ["Stakeholder interviews", "User interviews", "Personas", "User journey"],
                "body": "The opportunity was rooted in search behavior: millions of people were already looking for career information, but the experience around that intent was disconnected and uneven.",
            },
            {
                "chapter": "Chapter 2",
                "title": "Workshop",
                "tags": ["North star", "Roadmap"],
                "body": "Cross-functional workshops helped align business goals and user needs around a realistic multi-year north star rather than a collection of disconnected content improvements.",
            },
            {
                "chapter": "Chapter 3",
                "title": "Design",
                "tags": ["Flows", "Wireframes"],
                "body": "I focused on how information should be sequenced and how users move between role overviews, requirements, salary signals, and adjacent opportunities.",
            },
            {
                "chapter": "Chapter 4",
                "title": "Evaluative research",
                "tags": ["User testing"],
                "body": "Testing confirmed strong interest in using the product in the future, while also revealing a desire for more detailed guidance on how to start and progress in a given career.",
            },
            {
                "chapter": "Chapter 5",
                "title": "Milestones & iterations",
                "tags": ["Landing page", "Filters & sorting", "Company pages", "A/B tests"],
                "body": "Subsequent iterations improved search, filtering, and relevance, steadily raising performance and helping the experience scale to more markets and more content types.",
            },
        ],
        "gallery": [
            ("/assets/framer/images/ea7O6rnf4FCrFdcoG2vgVVkSWKw-ec9b5ff08c.png", "image"),
            ("/assets/framer/images/kgmRsi5qtroxTviFoxTTcWNeBqQ-9834a7fcd4.png", "image"),
            ("/assets/framer/images/HKMVAa3shASx1bz24oK8ro7chD0-af14756249.png", "image"),
            ("/assets/framer/images/syRJyIthKFQXYOgCEiXHzO8KegI-bf9dc22c72.png", "image"),
            ("/assets/framer/images/e1W23F3mTmpxaaSPdi9k6795M-24f39e8b89.png", "image"),
            ("/assets/framer/images/Bgen7hkcHKW4bDsQYhbIMnjds28-7230099749.png", "image"),
            ("/assets/framer/images/kzhxzIEAXBOSDcsSIHgFNHb8ypg-646fbb7430.png", "image"),
            ("/assets/framer/images/aHI2Avg5q2d7WTaptpmvnNp6Luk-f49d8965d1.png", "image"),
            ("/assets/framer/images/UizKuskjyAeIgXyUUQznmWTDVBQ-a0dc11589c.png", "image"),
            ("/assets/framer/images/ov9YhXl5UAa7e9jQn6CYrQM6oWE-360aac31f7.png", "image"),
        ],
        "retrospective": [
            "The north star mattered because the content surface area was so large.",
            "Career context needed to feel both inspirational and practical.",
            "Filters and sorting had outsized impact on perceived usefulness.",
        ],
    },
    {
        "slug": "content-collection",
        "eyebrow": "Indeed · cross-platform",
        "title": "Content Collection",
        "summary": "User generated content products that encourage job seekers to share their work experiences on Indeed.",
        "card_media": "/assets/framer/images/CdH8pMhtCcjtWyZOJS60R0kOAg-4994643a69.png",
        "hero_media": "/assets/framer/images/Ht4SH67a82umU8RointK1CSUPAw-d3631b3b37.png",
        "problem": "Create a more scalable, modular system for collecting useful job-seeker stories while balancing limited research and content design capacity.",
        "details": [
            ("My role", "Lead designer"),
            ("Duration", "4 quarters"),
            ("Responsibilities", "End-to-end process"),
            ("Constraints", "Limited content design and UX research resources"),
        ],
        "highlights": [
            ("5%", "Increase in content collection"),
            ("20+", "New design components"),
            ("10+", "Experiments shipped"),
        ],
        "sections": [
            {
                "chapter": "Chapter 1",
                "title": "Discovery",
                "tags": ["Beginner’s mindset", "Competitive analysis", "Evaluative research"],
                "body": "The first step was understanding where content lived today, what motivated contribution, and where the experience lost momentum or trust.",
            },
            {
                "chapter": "Chapter 2",
                "title": "Ideation",
                "tags": ["Workshop", "Design explorations"],
                "body": "Workshops were used to broaden the solution space and align cross-functional partners around where better prompts, structure, and modularity could unlock more contributions.",
            },
            {
                "chapter": "Chapter 3",
                "title": "Hi-fi design",
                "tags": ["Modular patterns"],
                "body": "The design system direction focused on repeatable collection patterns that could be reused across multiple contribution moments without reinventing the flow each time.",
            },
            {
                "chapter": "Chapter 4",
                "title": "Roadmap",
                "tags": ["Prioritization workshop"],
                "body": "Prioritization combined effort and impact to decide which experiments were worth pursuing first, helping the team sequence opportunities rationally.",
            },
            {
                "chapter": "Chapter 5",
                "title": "UX strategy",
                "tags": ["Long-term plan", "What and where"],
                "body": "The long-term strategy clarified where content should appear, what types of contribution mattered most, and how the system could keep scaling over time.",
            },
            {
                "chapter": "Chapter 6",
                "title": "Modular design system",
                "tags": ["Component library"],
                "body": "The end result was not just a one-off flow, but a composable collection toolkit that teams could extend into future experiments.",
            },
        ],
        "gallery": [
            ("/assets/framer/images/P59bcYRB2cGChGGYUIup2KT7WyU-9971ed27c9.png", "image"),
            ("/assets/framer/images/yBAKnrHoUlAuZatNi9u4A1W80-4805a23def.png", "image"),
            ("/assets/framer/images/YQIo7wJAfdJk7rSifSaXqn0LFg-e3f83995fd.png", "image"),
            ("/assets/framer/images/bIWEn6sKH3YRQmci0RhkuZR91ls-bf9dc22c72.png", "image"),
            ("/assets/framer/images/bA2rGcuHewAXxzXEcUuxUqKVMWo-d3631b3b37.png", "image"),
            ("/assets/framer/images/MsNlLuMNuveh2enGG6QhFkEEDU-bf9dc22c72.png", "image"),
            ("/assets/framer/images/ezamQWHw64x6q1Pk0nBpVN49US8-f68ee82663.png", "image"),
        ],
        "retrospective": [
            "Modularity mattered as much as conversion rate.",
            "A small team needed sharper prioritization discipline.",
            "The system approach made future experiments cheaper and faster.",
        ],
    },
]


EXPERIMENTS = [
    {
        "title": "VR concert experiences",
        "subtitle": "A product idea for high-quality and accessible concert experiences",
        "media": "/assets/framer/images/lauP5CGG3jAZYpsz1OcMaQrdzA-dc00bc0da6.png",
    },
    {
        "title": "AI-generated accessories",
        "subtitle": "A series of fashion accessories inspired by Nike and Futurism",
        "media": "/assets/framer/images/xw3vcQDVxzU3IK79sh7t0EbMOtE-dc00bc0da6.png",
    },
    {
        "title": "Seaweed leather",
        "subtitle": "Cruelty-free fashion concepts made from seaweed-based material",
        "media": "/assets/framer/images/BBeCVOg2iG0ZHDYEYFRHkc42U-dc00bc0da6.png",
    },
    {
        "title": "AI-powered moonwalkers",
        "subtitle": "Moonwalkers that adapt to your walking and running preferences",
        "media": "/assets/framer/images/YKGCy8lWEF8yIRPXsCKaTYAOBnA-dc00bc0da6.jpg",
    },
]


ABOUT = {
    "portrait": "/assets/framer/images/ioh8OB4Ezx7i1EmiSa1kJppyrJ8-3c0db6a87e.png",
    "intro_label": "He/Him",
    "intro_title": "Hi there! I’m Konrad, a Digital Product Designer",
    "intro_body": "I’m a product designer working at the intersection of design, systems, and technology. Over the past decade I’ve helped shape products across startups, marketplaces, enterprise tools, and public services.",
    "principles": [
        ("Be considerate", "Show care for every person who uses your products. Recognize exclusions and create inclusive experiences."),
        ("Build trust", "Be genuine and transparent. Show users and stakeholders that you act in their best interests."),
        ("Create consistency", "Use familiar patterns to make experiences recognizable. Help your teams achieve goals with less effort."),
    ],
    "experience": [
        ("Oct 2025 – Present", "Product Designer 6-2", "OKX"),
        ("Jul 2023 – Sep 2025", "Principal Product Designer", "GovTech Singapore"),
        ("Jun 2019 – Jun 2023", "Senior Product Designer", "Indeed"),
        ("Aug 2017 – May 2019", "Product Designer", "Grab"),
        ("Mar 2016 – Jul 2017", "Product Designer", "99.co"),
        ("Feb 2015 – Dec 2015", "Product Designer", "Present – Social Video Diary"),
        ("Apr 2014 – Feb 2015", "UX Designer", "Free Flow Research"),
    ],
    "publications": [
        ("Konrad Marzec: AI doesn’t kill creativity", "Vogue"),
        ("Beyond Boundaries: Diversity & AI in Fashion", "Vogue"),
        ("Konrad Marzec and His Next Level Digital Designs", "Overstandard"),
        ("7 Business benefits of inclusive design", "Indeed Design Blog"),
        ("Design case study in a Singaporean Startup", "UX Collective"),
        ("Let's talk about designing Customer Support Experience", "UX Collective"),
    ],
    "skills": ["Stakeholder management", "Interaction design", "Information architecture"],
}


HOME = {
    "hero_title": "你好！我是吕晓维",
    "hero_body": "一名有10年工作经验的产品设计师，近5年就职于知乎，主负责知乎核心消费场景（问答页）和社交方向的设计，擅长在复杂系统中关注用户行为与平台生态设计，在体验细节、业务目标与长期社区价值之间建立平衡，持续推动内容、社交与平台型产品的体验升级。",
    "hero_media": "/assets/framer/images/home-hero.png",
    "showreel": "/assets/framer/assets/qmNVzBBo2CSFLiXgZlEATXcHxYY.mp4",
    "featured_section_title": "精选作品",
    "featured_cards": [
        {
            "slug": "solace",
            "eyebrow": "复杂系统设计 · 内容消费升级 · 复杂产品决策力",
            "title": "知乎问答详情页容器重构",
            "summary": "通过重构知乎问答详情页核心结构，优化高密度内容场景下的信息组织与消费路径，在复杂业务约束下提升用户消费效率和消费深度，并增强平台整体内容分发与商业转化能力",
            "card_media": "/assets/custom/case-1.png",
            "href": "/work/zhihu-detail-container-rebuild/",
            "button_label": "查看作品",
        },
        {
            "slug": "parkit",
            "eyebrow": "提升互动率 · 用户表达 · 社区长期价值",
            "title": "知乎互动bar改版",
            "summary": "围绕知乎社区表达机制，对互动 Bar 进行系统性升级，在用户表达效率、内容互动体验与社区长期价值之间建立平衡，统一多内容场景下的互动表达体系。",
            "card_media": "/assets/custom/case-2.png",
            "href": "/work/zhihu-interaction-bar-revamp-2026/",
            "button_label": "查看作品",
        },
        {
            "slug": "work-well-being",
            "eyebrow": "社交表达方向 · 关系链路设计 · 兴趣社区设计",
            "title": "知乎社交设计",
            "summary": "围绕知乎弱连接社区关系，对个人页、互动表达与兴趣场景进行系统性升级，强化用户身份感、信任感与关系建立效率，推动内容消费向长期社区参与转化。",
            "card_media": "/assets/custom/case-3.png",
            "href": "/work/interest-circle-community/",
            "button_label": "查看作品",
        },
        {
            "slug": "grab",
            "eyebrow": "桌面阅读体验 · 内容消费升级 · 体验策略",
            "title": "知乎 PC 端整体体验升级",
            "summary": "从桌面阅读场景与办公语境出发，重构知乎 PC 端的导航、布局与视觉语言，建立更低噪音、更内容优先的长期阅读体验。",
            "card_media": "/assets/custom/case-4.png",
            "href": "/work/zhihu-pc-reading-experience-revamp/",
            "button_label": "查看作品",
        },
    ],
    "archive_cards": [
        ("Grab", "Drive Southeast Asia Forward"),
        ("Present", "Capture Every Minute"),
        ("99.co", "Your Way Home"),
    ],
    "archive_period": "2015～2019",
    "archive_title": "更早期的作品",
    "archive_body": "早期专注于金融产品与增长设计，围绕用户转化、信任建立与复杂流程体验进行持续优化。\n这段经历让我逐渐建立起对复杂用户行为与全流程产品设计的系统性理解。",
    "archive_cta": "查看作品",
    "archive_cta_href": "/case-studies/earlier-work/",
    "archive_gallery": [
        "/assets/custom/yinni1.png",
        "/assets/custom/yinni2.png",
        "/assets/custom/yinni3.png",
        "/assets/custom/yinni4.png",
        "/assets/custom/yinni5.png",
    ],
}


LEGACY_PORTFOLIO_PAGE = {
    "hero_period": "2015～2019",
    "hero_title": "金融与增长设计作品",
    "hero_body": "早期专注于金融产品与增长设计，围绕用户转化、信任建立与复杂流程体验进行持续优化。这段经历让我逐渐建立起对复杂用户行为与全流程产品设计的系统性理解。",
    "hero_stats": [
        ("工作重心", "金融产品 / 增长设计"),
        ("核心议题", "转化、信任、复杂流程"),
        ("设计方式", "策略到落地的全链路推进"),
    ],
    "feature_cards": [
        {
            "eyebrow": "独立开发",
            "title": "空气时钟-翻页时钟小组件",
            "body": "桌面时钟 &数码时间显示",
            "meta": "独立开发",
            "media": "/assets/case-study/air1.png",
            "href": "/work/air-oclock/",
        },
        {
            "eyebrow": "精选方向 02",
            "title": "增长活动与转化承接设计",
            "body": "把活动入口、权益表达与落地页承接打通，减少用户在营销流量进入后的认知跳跃与操作流失。",
            "meta": "活动承接 · 价值表达 · 漏斗优化",
            "media": "/assets/custom/yinni3.png",
        },
    ],
    "practice_cards": [
        {
            "eyebrow": "方法一",
            "title": "把复杂决策拆成可前进的步骤",
            "body": "面对高风险、高顾虑场景，我会优先重组信息顺序与任务节奏，让用户在每一步都知道自己为什么继续。",
        },
        {
            "eyebrow": "方法二",
            "title": "先建立信任，再推动转化",
            "body": "通过收益解释、风险表达、状态反馈与细节一致性，让产品不是只会“催促点击”，而是能帮助用户放心决策。",
        },
        {
            "eyebrow": "方法三",
            "title": "从局部页面扩展到完整链路",
            "body": "不只优化单一界面，而是同时看入口、承接、转化与结果页之间的关系，确保体验和业务目标真正连起来。",
        },
    ],
    "project_cards": [
        {
            "eyebrow": "项目模块 A",
            "title": "金融产品体验升级",
            "body": "聚焦借贷、授信与核心操作链路，在高约束业务里提升信息可理解性、操作效率和决策完成率。",
            "tags": ["全流程体验", "信息分层", "本地化表达"],
        },
        {
            "eyebrow": "项目模块 B",
            "title": "增长页面与活动专题",
            "body": "围绕拉新、促活与转化场景设计专题页与落地页，让营销触点和产品内体验保持同一叙事与同一节奏。",
            "tags": ["专题设计", "活动承接", "转化优化"],
        },
        {
            "eyebrow": "项目模块 C",
            "title": "品牌视觉与界面规范探索",
            "body": "在持续业务迭代中建立更稳定的视觉表达与通用组件思路，让不同项目之间的体验质量逐步拉齐。",
            "tags": ["视觉规范", "组件沉淀", "一致性提升"],
        },
    ],
    "gallery_title": "完整作品预览",
    "gallery_body": "下方保留原始作品长图，方便继续查看更完整的页面细节、运营专题和界面输出。",
}


EXPERIMENTS_PAGE = {
    "hero_title": "Experiments",
    "hero_body": "Exploring the intersection of motion, interaction, and visual design through experimental work with various tools.",
    "feature_cards": [
        {
            "title": "By Designers",
            "subtitle": "Design can be art",
            "media": "/assets/framer/images/c24umtTpNkBqnjNnW0wcqDiN83U.png",
        },
        {
            "title": "Coaching sessions",
            "subtitle": "125 sessions delivered across five months",
            "media": "/assets/framer/images/nsrPYVTZMStiAxlUIkLPdy4uVI.png",
        },
        {
            "title": "101 Design",
            "subtitle": "Micro interactions matter",
            "media": "/assets/framer/images/9MoVy7zKoDkQ6JooFX3a3rOrxU-1a38458852.png",
        },
        {
            "title": "Backpack X01",
            "subtitle": "Experimental object storytelling",
            "media": "/assets/framer/images/lFqvt6jd1Q1lc2N27GTKfytlDzA.png",
        },
        {
            "title": "English",
            "subtitle": "Design is not rocket science, but it is science",
            "media": "/assets/framer/images/ihN46Zr147HztFQAw31QGKZLns.png",
        },
        {
            "title": "Chinese",
            "subtitle": "Poster explorations in motion and type",
            "media": "/assets/framer/images/MLloAwdISO9vxn8uAlUNgh2RZmY.png",
        },
    ],
}
